---@meta

---@class ADigger_BP_C : ADigger
---@field UberGraphFrame FPointerToUberGraphFrame
---@field NewVehicleMovementObstacle UBoxComponent
---@field Exhaust1 USkeletalMeshComponent
---@field exhaust USkeletalMeshComponent
---@field turbo UAudioComponent
---@field ShovelDustBurst4 UParticleSystemComponent
---@field ShovelDustBurst3 UParticleSystemComponent
---@field CoolingR UParticleSystemComponent
---@field CoolingL UParticleSystemComponent
---@field OverHeatedL UParticleSystemComponent
---@field OverHeatedR UParticleSystemComponent
---@field SM_Digger_Sand UStaticMeshComponent
---@field Finish UAudioComponent
---@field kopanie UAudioComponent
---@field Accessories USkeletalMeshComponent
---@field Beard USkeletalMeshComponent
---@field Hair USkeletalMeshComponent
---@field LowerArm USkeletalMeshComponent
---@field UpperArm USkeletalMeshComponent
---@field UpperBody USkeletalMeshComponent
---@field LowerLeg USkeletalMeshComponent
---@field UpperLeg USkeletalMeshComponent
---@field LowerBody USkeletalMeshComponent
---@field SkeletalMesh USkeletalMeshComponent
---@field CrashEngine UAudioComponent
---@field Silence UAudioComponent
---@field SandOverlappingBox UBoxComponent
---@field ShovelDustBurst2 UParticleSystemComponent
---@field ShovelDustBurst1 UParticleSystemComponent
---@field ShovelDust UParticleSystemComponent
---@field EngineVFX1 UParticleSystemComponent
---@field EngineVFX UParticleSystemComponent
---@field Heat2 UParticleSystemComponent
---@field Heat1 UParticleSystemComponent
---@field DYmek2 UParticleSystemComponent
---@field DYmek1 UParticleSystemComponent
---@field DiggerDrop UAudioComponent
---@field StartEngineSound UAudioComponent
---@field StopEngineSound UAudioComponent
---@field EngineSound UAudioComponent
---@field BackLight2 UStaticMeshComponent
---@field BackLight1 UStaticMeshComponent
---@field FrontLight2 UStaticMeshComponent
---@field FrontLight1 UStaticMeshComponent
---@field SpotLight2 USpotLightComponent
---@field SpotLight1 USpotLightComponent
---@field Arrow_SRC UArrowComponent
---@field Box UBoxComponent
---@field Timeline_0_NewHeatValue_C9D7319E43B7335F8ECB4693130CACA1 float
---@field Timeline_0__Direction_C9D7319E43B7335F8ECB4693130CACA1 ETimelineDirection::Type
---@field Timeline_0 UTimelineComponent
---@field ReduceColorTest_Color_E2A6254F41E892350DEF9DBC00C6AC7B float
---@field ReduceColorTest__Direction_E2A6254F41E892350DEF9DBC00C6AC7B ETimelineDirection::Type
---@field ReduceColorTest UTimelineComponent
---@field EmptyMinigameActive boolean
---@field FillMinigameActive boolean
---@field bHolding boolean
---@field CanBeEmpty boolean
---@field ExhaustGlowMaterial UMaterialInstanceDynamic
---@field FrontLightIntensity float
---@field AdditionalLightsFront_MaterialInstance UMaterialInstanceDynamic
---@field AdditionalLightsBack_MaterialInstance UMaterialInstanceDynamic
---@field WhiteColor FLinearColor
---@field BlackColor FLinearColor
---@field StandardSpeed_0 float
---@field BoostSpeed_0 float
---@field OverheatSpeedWhenSprint_0 float
---@field OverheatRMBRemovalMultiplier float
---@field ShovelSpeedMultiplier float
---@field TimeToMoveCameraToOriginalSlot float
---@field FuelRemoveSpeed_0 float
---@field bPlayingEmptyingMontage boolean
---@field PitchSoundTimer FTimerHandle
---@field InitAIController AAIController
---@field CoolEngineOnUnpossesTimer FTimerHandle
local ADigger_BP_C = {}

---@param DiggerHasLowVelocity boolean
function ADigger_BP_C:HandleOverlappingSand(DiggerHasLowVelocity) end
function ADigger_BP_C:StopIfFuelEmpty() end
function ADigger_BP_C:SetInteractionManagerInputMode() end
function ADigger_BP_C:FadeOutVelocityIfUnpossesed() end
function ADigger_BP_C:StopIfUnpossesed() end
---@return FName
function ADigger_BP_C:GetInteractionName() end
---@return ACharacter
function ADigger_BP_C:GetBPOriginalCharacter() end
---@param BeActivate boolean
function ADigger_BP_C:VFXdust_drive(BeActivate) end
---@param DeltaTime float
function ADigger_BP_C:ResetCameraLocationOverTime(DeltaTime) end
function ADigger_BP_C:HandbrakeReleased() end
function ADigger_BP_C:HandbrakePressed() end
function ADigger_BP_C:VFX_CoolingCheck() end
---@param DeltaTime float
function ADigger_BP_C:OverheatFasterRemoval(DeltaTime) end
---@param Input float
---@param NewParam boolean
function ADigger_BP_C:AllowMove(Input, NewParam) end
function ADigger_BP_C:UserConstructionScript() end
function ADigger_BP_C:ReduceColorTest__FinishedFunc() end
function ADigger_BP_C:ReduceColorTest__UpdateFunc() end
function ADigger_BP_C:Timeline_0__FinishedFunc() end
function ADigger_BP_C:Timeline_0__UpdateFunc() end
---@param Key FKey
function ADigger_BP_C:InpActEvt_Nine_K2Node_InputKeyEvent_2(Key) end
---@param Key FKey
function ADigger_BP_C:InpActEvt_Zero_K2Node_InputKeyEvent_1(Key) end
---@param Key FKey
function ADigger_BP_C:InpActEvt_Eight_K2Node_InputKeyEvent_0(Key) end
---@param NotifyName FName
function ADigger_BP_C:OnNotifyEnd_228231E340467873746E75AB1505AE68(NotifyName) end
---@param NotifyName FName
function ADigger_BP_C:OnNotifyBegin_228231E340467873746E75AB1505AE68(NotifyName) end
---@param NotifyName FName
function ADigger_BP_C:OnInterrupted_228231E340467873746E75AB1505AE68(NotifyName) end
---@param NotifyName FName
function ADigger_BP_C:OnBlendOut_228231E340467873746E75AB1505AE68(NotifyName) end
---@param NotifyName FName
function ADigger_BP_C:OnCompleted_228231E340467873746E75AB1505AE68(NotifyName) end
---@param Loaded UClass
function ADigger_BP_C:OnLoaded_70DD20A14FED90D7169807B1F32B1973(Loaded) end
---@param DeltaSeconds float
function ADigger_BP_C:ReceiveTick(DeltaSeconds) end
---@param NewController AController
function ADigger_BP_C:ReceivePossessed(NewController) end
---@param OldController AController
function ADigger_BP_C:ReceiveUnpossessed(OldController) end
function ADigger_BP_C:Empty() end
function ADigger_BP_C:Full() end
function ADigger_BP_C:ReceiveBeginPlay() end
function ADigger_BP_C:EngineFix() end
function ADigger_BP_C:StopEngine() end
function ADigger_BP_C:ScaleSandWhileEmptying() end
function ADigger_BP_C:SoundPitchDown() end
function ADigger_BP_C:SandScaling() end
function ADigger_BP_C:StopBoostOnEngineCrash() end
function ADigger_BP_C:BoostBlueprintEvent() end
---@param bPressed boolean
function ADigger_BP_C:InputActionPrimary(bPressed) end
---@param bPressed boolean
function ADigger_BP_C:InputActionInteraction(bPressed) end
---@param bPressed boolean
function ADigger_BP_C:InputActionSecondary(bPressed) end
---@param Value float
function ADigger_BP_C:InputActionMoveForward(Value) end
function ADigger_BP_C:EngineCrash() end
function ADigger_BP_C:EngineColor() end
function ADigger_BP_C:OverheatHandling() end
function ADigger_BP_C:CoolEngineOnUnposses() end
---@param bShowSand boolean
function ADigger_BP_C:ShowSand(bShowSand) end
---@param EntryPoint int32
function ADigger_BP_C:ExecuteUbergraph_Digger_BP(EntryPoint) end


