---@meta

---@class UGSS_PlayerOverlay_WBP_C : UGSS_PlayerOverlay
---@field UberGraphFrame FPointerToUberGraphFrame
---@field HideQuestHolder UWidgetAnimation
---@field OveralFadeUI UWidgetAnimation
---@field Airplanes_Widget_WBP UAirplanes_Widget_WBP_C
---@field AlarmWidgetSizer USizeBox
---@field CanvasPanel_16 UCanvasPanel
---@field DirtyHolder UHorizontalBox
---@field HappyHolder UHorizontalBox
---@field HorizontalboxQuestsAndChallenges UHorizontalBox
---@field Image UImage
---@field Image_773 UImage
---@field InvalidationBox_0 UInvalidationBox
---@field InvalidationBox_1 UInvalidationBox
---@field InvalidationBox_Photo UInvalidationBox
---@field MainGameChallengeSizebox USizeBox
---@field Money_Widget UMoney_Widget_WBP_C
---@field PC_Notification_195 UPC_Notification_C
---@field QuestHolderSizeBox USizeBox
---@field ScreenVersion UTextBlock
---@field StationTrafficMeter_Widget UStationTrafficMeter_Widget_C
---@field TabHolder UScaleBox
---@field Time_Widget UTime_Widget_C
---@field VerticalBox_0 UVerticalBox
---@field VerticalBox_MoreInfo UVerticalBox
---@field VerticalBox_QuestsAndChallenges UVerticalBox
---@field WBP_CarSold UWBP_CarSold_C
---@field WBP_ChallengesHolder UWBP_ChallengesHolder_C
---@field WBP_CinemaConfirmation UWBP_CinemaConfirmation_C
---@field WBP_CustomerDie_Notification UWBP_CustomerDie_Notification_C
---@field WBP_HoldToHide UWBP_HideQuestHolderHint_C
---@field WBP_KeyBindedAction_BugReport UWBP_KeyBindedAction_C
---@field WBP_KeyBindedAction_MoreInfo UWBP_KeyBindedAction_C
---@field WBP_NewFameLevelPopup UWBP_NewFameLevelPopup_C
---@field WBP_PhotoBinding UWBP_PhotoBinding_C
---@field WBP_QuestHidden_1 UWBP_ShowQuestHolder_C
---@field WBP_QuestHolder UWBP_QuestHolder_C
---@field EngineCursorREF UCursorWidget_C
---@field VolcanoTutorialRef UMiniGames_Tutorial_C
---@field RentalTutorialRef UMiniGames_Tutorial_C
---@field VolcanoTutorialTimer FTimerHandle
---@field RentalTutorialTimer FTimerHandle
---@field VIPBonusWidget UUserWidget
local UGSS_PlayerOverlay_WBP_C = {}

---@param A FName
function UGSS_PlayerOverlay_WBP_C:CheckBIndings(A) end
function UGSS_PlayerOverlay_WBP_C:ToggleMoreInfo() end
---@param Loaded UClass
function UGSS_PlayerOverlay_WBP_C:OnLoaded_13858A4745674026813ACFB4A9CEF199(Loaded) end
function UGSS_PlayerOverlay_WBP_C:Construct() end
function UGSS_PlayerOverlay_WBP_C:RefreshRunway() end
---@param InVisibility ESlateVisibility
function UGSS_PlayerOverlay_WBP_C:HideWhitePointer(InVisibility) end
function UGSS_PlayerOverlay_WBP_C:LoadHappyWidgetPerMap() end
function UGSS_PlayerOverlay_WBP_C:LoadDirtyWidgetPerMap() end
function UGSS_PlayerOverlay_WBP_C:ShowVolcanoTutorial() end
function UGSS_PlayerOverlay_WBP_C:VolcanoTutorialClosed() end
function UGSS_PlayerOverlay_WBP_C:TryOpenVolcanoTutorial() end
function UGSS_PlayerOverlay_WBP_C:ShowRentalTutorial() end
function UGSS_PlayerOverlay_WBP_C:TryOpenRentalTutorial() end
function UGSS_PlayerOverlay_WBP_C:RentalTutorialClosed() end
---@param bVisible boolean
function UGSS_PlayerOverlay_WBP_C:ShowLeftCornerBindings(bVisible) end
---@param bVisible boolean
function UGSS_PlayerOverlay_WBP_C:ToggleCinemaInteractionInfo(bVisible) end
function UGSS_PlayerOverlay_WBP_C:CreateVIPBonusWidget() end
function UGSS_PlayerOverlay_WBP_C:DestroyVIPBonusWidget() end
function UGSS_PlayerOverlay_WBP_C:CheckRedDotAlarm() end
---@param NewUnlockableUIState FUnlockableUIState
function UGSS_PlayerOverlay_WBP_C:OnNewUnlockableUIStateSet(NewUnlockableUIState) end
function UGSS_PlayerOverlay_WBP_C:ToggleTrafficMeterDebug() end
---@param FollowedQuestLine UActiveQuestLine
function UGSS_PlayerOverlay_WBP_C:HideChallegnes(FollowedQuestLine) end
function UGSS_PlayerOverlay_WBP_C:FoldQuestAndChallengesHolder() end
function UGSS_PlayerOverlay_WBP_C:CheckQuestHolderStatus() end
---@param IsDesignTime boolean
function UGSS_PlayerOverlay_WBP_C:PreConstruct(IsDesignTime) end
---@param QuestStarted UQuestBase
function UGSS_PlayerOverlay_WBP_C:CustomEvent_2(QuestStarted) end
function UGSS_PlayerOverlay_WBP_C:Reset() end
---@param ActionName FName
function UGSS_PlayerOverlay_WBP_C:OnKeyChanged(ActionName) end
---@param EntryPoint int32
function UGSS_PlayerOverlay_WBP_C:ExecuteUbergraph_GSS_PlayerOverlay_WBP(EntryPoint) end


