---@meta

---@class UNPC_AnimationManager_C : UNPCAnimationManagerBase
---@field UberGraphFrame FPointerToUberGraphFrame
---@field ShouldRotateYaw boolean
---@field AnimCurveName FName
---@field StartingRotation FRotator
---@field DesiredRotation FRotator
---@field ShouldPosition boolean
---@field PositionToGo FVector
---@field OwnerPosition FVector
---@field Chair AChair_Bp_C
---@field isSitting boolean
---@field SpawnedProp AActor
---@field SocketPosition FVector
---@field SocketRotation FRotator
---@field SpawnedEmitter UParticleSystemComponent
---@field ParticleSocket FName
---@field StartingTransform FTransform
---@field DesiredTransform FTransform
---@field ['Montages Skeletons'] TArray<FBaseCharacterSkeletonMontage>
---@field AICharacterBase AAICharacterBase
---@field ['Tag to Check'] FGameplayTag
local UNPC_AnimationManager_C = {}

---@param SittingTarget AActor
function UNPC_AnimationManager_C:HandleSittingMontages(SittingTarget) end
function UNPC_AnimationManager_C:SetOwningCharacter() end
---@param SameFacing boolean
function UNPC_AnimationManager_C:CheckFacing(SameFacing) end
---@param CarEnterT FTransform
---@param DriverPositionT FTransform
---@param PawnTransform FTransform
function UNPC_AnimationManager_C:GetCarInfo(CarEnterT, DriverPositionT, PawnTransform) end
---@param ExtraTime float
---@param NoMontageWaitTime float
---@return float
function UNPC_AnimationManager_C:GetMontageLength(ExtraTime, NoMontageWaitTime) end
---@param Character_Gender ECharacterGender
UNPC_AnimationManager_C['Get Gender'] = function(self, Character_Gender) end
function UNPC_AnimationManager_C:AttachParticleSystem() end
function UNPC_AnimationManager_C:DestroyParticle() end
---@param Socket FName
---@param EmitterTemplate UParticleSystem
UNPC_AnimationManager_C['Spawn Particle'] = function(self, Socket, EmitterTemplate) end
---@param Output_Get UAnimMontage
function UNPC_AnimationManager_C:GetCurrentActiveMontage(Output_Get) end
---@param LookAt_ boolean
function UNPC_AnimationManager_C:SetLookatbool(LookAt_) end
---@param AsNPC_Ai_Master_Anim_Bp UNPC_Ai_MasterAnimBp_C
function UNPC_AnimationManager_C:GetOwnerAnimBp(AsNPC_Ai_Master_Anim_Bp) end
---@param HitReact boolean
function UNPC_AnimationManager_C:SetCanPlayHitReact(HitReact) end
---@param IdleNumberOut int32
function UNPC_AnimationManager_C:CalculateIdleRandomChance(IdleNumberOut) end
function UNPC_AnimationManager_C:DestroyProp() end
---@param TimeToDestroy float
function UNPC_AnimationManager_C:DeAttachProp(TimeToDestroy) end
---@param SocketName FName
---@param ClassToSpawn TSubclassOf<AActor>
---@param SpawnedPropRef AActor
function UNPC_AnimationManager_C:SpawnProp(SocketName, ClassToSpawn, SpawnedPropRef) end
---@param SkeletalMesh USkeletalMeshComponent
function UNPC_AnimationManager_C:getOwnerSkeletalMesh(SkeletalMesh) end
---@param ShouldLookAt boolean
function UNPC_AnimationManager_C:SetShouldLookAt(ShouldLookAt) end
function UNPC_AnimationManager_C:DisableOwnerCollision() end
function UNPC_AnimationManager_C:Rotate() end
---@param DesiredLocation FVector
function UNPC_AnimationManager_C:test(DesiredLocation) end
---@param VectorToMoveTo FVector
---@param OwnerPosition FVector
function UNPC_AnimationManager_C:StartPositioning(VectorToMoveTo, OwnerPosition) end
---@param OwnerPosition FVector
function UNPC_AnimationManager_C:GetOwnerPosition(OwnerPosition) end
function UNPC_AnimationManager_C:StartYawRotation() end
UNPC_AnimationManager_C['Stop Yaw Rotation'] = function(self, ) end
---@param StartingRotation FRotator
function UNPC_AnimationManager_C:GetOwnerRotation(StartingRotation) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyEnd_3FBD8B2342B903B342E8E89E99B54A7C(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyBegin_3FBD8B2342B903B342E8E89E99B54A7C(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnInterrupted_3FBD8B2342B903B342E8E89E99B54A7C(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnBlendOut_3FBD8B2342B903B342E8E89E99B54A7C(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnCompleted_3FBD8B2342B903B342E8E89E99B54A7C(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyEnd_B30C8C23454B5790F6EC96AD3176F7A4(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyBegin_B30C8C23454B5790F6EC96AD3176F7A4(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnInterrupted_B30C8C23454B5790F6EC96AD3176F7A4(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnBlendOut_B30C8C23454B5790F6EC96AD3176F7A4(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnCompleted_B30C8C23454B5790F6EC96AD3176F7A4(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyEnd_802B13AE45D8F1F90D0AFDB9946FFC96(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyBegin_802B13AE45D8F1F90D0AFDB9946FFC96(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnInterrupted_802B13AE45D8F1F90D0AFDB9946FFC96(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnBlendOut_802B13AE45D8F1F90D0AFDB9946FFC96(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnCompleted_802B13AE45D8F1F90D0AFDB9946FFC96(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyEnd_83D1E5FE4C48B347E4BB0392EDF1AB4F(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyBegin_83D1E5FE4C48B347E4BB0392EDF1AB4F(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnInterrupted_83D1E5FE4C48B347E4BB0392EDF1AB4F(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnBlendOut_83D1E5FE4C48B347E4BB0392EDF1AB4F(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnCompleted_83D1E5FE4C48B347E4BB0392EDF1AB4F(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyEnd_587678D3405DE781DD317A918C58856A(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyBegin_587678D3405DE781DD317A918C58856A(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnInterrupted_587678D3405DE781DD317A918C58856A(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnBlendOut_587678D3405DE781DD317A918C58856A(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnCompleted_587678D3405DE781DD317A918C58856A(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyEnd_44950C7F424FB144D9C5F1AB39FF7862(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyBegin_44950C7F424FB144D9C5F1AB39FF7862(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnInterrupted_44950C7F424FB144D9C5F1AB39FF7862(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnBlendOut_44950C7F424FB144D9C5F1AB39FF7862(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnCompleted_44950C7F424FB144D9C5F1AB39FF7862(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyEnd_DAC506384464313594F5399A769A5671(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyBegin_DAC506384464313594F5399A769A5671(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnInterrupted_DAC506384464313594F5399A769A5671(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnBlendOut_DAC506384464313594F5399A769A5671(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnCompleted_DAC506384464313594F5399A769A5671(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyEnd_8F94E27243A38ED6D0B9A0BECA9A790F(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyBegin_8F94E27243A38ED6D0B9A0BECA9A790F(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnInterrupted_8F94E27243A38ED6D0B9A0BECA9A790F(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnBlendOut_8F94E27243A38ED6D0B9A0BECA9A790F(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnCompleted_8F94E27243A38ED6D0B9A0BECA9A790F(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyEnd_CF6C748947315AB8582BB880935B7762(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyBegin_CF6C748947315AB8582BB880935B7762(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnInterrupted_CF6C748947315AB8582BB880935B7762(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnBlendOut_CF6C748947315AB8582BB880935B7762(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnCompleted_CF6C748947315AB8582BB880935B7762(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyEnd_DBD7A27849ACB5083C1C1DBDA5AC638C(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyBegin_DBD7A27849ACB5083C1C1DBDA5AC638C(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnInterrupted_DBD7A27849ACB5083C1C1DBDA5AC638C(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnBlendOut_DBD7A27849ACB5083C1C1DBDA5AC638C(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnCompleted_DBD7A27849ACB5083C1C1DBDA5AC638C(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyEnd_C29B6E274741B64BAAB86D95E777E1F5(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyBegin_C29B6E274741B64BAAB86D95E777E1F5(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnInterrupted_C29B6E274741B64BAAB86D95E777E1F5(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnBlendOut_C29B6E274741B64BAAB86D95E777E1F5(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnCompleted_C29B6E274741B64BAAB86D95E777E1F5(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyEnd_75967A364D06EC1CEB588D854D2B11FD(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnNotifyBegin_75967A364D06EC1CEB588D854D2B11FD(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnInterrupted_75967A364D06EC1CEB588D854D2B11FD(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnBlendOut_75967A364D06EC1CEB588D854D2B11FD(NotifyName) end
---@param NotifyName FName
function UNPC_AnimationManager_C:OnCompleted_75967A364D06EC1CEB588D854D2B11FD(NotifyName) end
function UNPC_AnimationManager_C:ReceiveBeginPlay() end
---@param SkeletalMesh USkeletalMeshComponent
---@param Montage UAnimMontage
---@param TimeToStopRotation float
---@param PlayRate float
---@param AnimCurveName FName
---@param DesiredRotation FRotator
function UNPC_AnimationManager_C:PlayMontageWithYawRotation(SkeletalMesh, Montage, TimeToStopRotation, PlayRate, AnimCurveName, DesiredRotation) end
---@param SkeletalMesh USkeletalMeshComponent
---@param MontageToPlay UAnimMontage
---@param NewPosition FVector
---@param Offset FVector
function UNPC_AnimationManager_C:PlayMontageAndPosition(SkeletalMesh, MontageToPlay, NewPosition, Offset) end
function UNPC_AnimationManager_C:StandUp() end
function UNPC_AnimationManager_C:CalculateRandomIdle() end
---@param ShouldPosition boolean
---@param PositionToGo FVector
function UNPC_AnimationManager_C:PositionOwner(ShouldPosition, PositionToGo) end
---@param MontageToPlay UAnimMontage
---@param PlayRate float
---@param StartingPosition float
---@param StartingSection FName
---@param StartingTransform FTransform
---@param DesiredTransform FTransform
function UNPC_AnimationManager_C:GssMontagePlayWithPosition(MontageToPlay, PlayRate, StartingPosition, StartingSection, StartingTransform, DesiredTransform) end
---@param SittingTarget AActor
function UNPC_AnimationManager_C:StartSitting(SittingTarget) end
function UNPC_AnimationManager_C:EndSitting() end
---@param EntryPoint int32
function UNPC_AnimationManager_C:ExecuteUbergraph_NPC_AnimationManager(EntryPoint) end


