---@meta

---@class UNPC_Ai_MasterAnimBp_C : UHumanAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_UseCachedPose_7 FAnimNode_UseCachedPose
---@field AnimGraphNode_Inertialization FAnimNode_Inertialization
---@field AnimGraphNode_SaveCachedPose_6 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LocalToComponentSpace FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_SaveCachedPose_5 FAnimNode_SaveCachedPose
---@field AnimGraphNode_SaveCachedPose_4 FAnimNode_SaveCachedPose
---@field AnimGraphNode_SequencePlayer_17 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_27 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_5 FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose_3 FAnimNode_SaveCachedPose
---@field AnimGraphNode_DragonAimSolver FAnimNode_DragonAimSolver
---@field AnimGraphNode_ModifyBone_1 FAnimNode_ModifyBone
---@field AnimGraphNode_TransitionResult_39 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_38 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_37 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_36 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_35 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_34 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_33 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_32 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_31 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_30 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_29 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_28 FAnimNode_TransitionResult
---@field AnimGraphNode_RandomPlayer_1 FAnimNode_RandomPlayer
---@field AnimGraphNode_StateResult_26 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_16 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_25 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_15 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_24 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_14 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_23 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_13 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_22 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_12 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_21 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_11 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_20 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_1 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_19 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_4 FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose_2 FAnimNode_SaveCachedPose
---@field AnimGraphNode_Slot_2 FAnimNode_Slot
---@field AnimGraphNode_LayeredBoneBlend FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_Slot_1 FAnimNode_Slot
---@field AnimGraphNode_SaveCachedPose_1 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_6 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_5 FAnimNode_UseCachedPose
---@field AnimGraphNode_HandIKRetargeting FAnimNode_HandIKRetargeting
---@field AnimGraphNode_TwoBoneIK_1 FAnimNode_TwoBoneIK
---@field AnimGraphNode_TwoBoneIK FAnimNode_TwoBoneIK
---@field AnimGraphNode_ModifyBone FAnimNode_ModifyBone
---@field AnimGraphNode_ComponentToLocalSpace FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_TransitionResult_27 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_26 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_25 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_24 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_23 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_22 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_10 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_18 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_9 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_17 FAnimNode_StateResult
---@field AnimGraphNode_RandomPlayer FAnimNode_RandomPlayer
---@field AnimGraphNode_StateResult_16 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_3 FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose FAnimNode_SaveCachedPose
---@field AnimGraphNode_SequencePlayer_8 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_15 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_14 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_2 FAnimNode_StateMachine
---@field AnimGraphNode_TransitionResult_21 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_20 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_19 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_18 FAnimNode_TransitionResult
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field AnimGraphNode_PoseSnapshot FAnimNode_PoseSnapshot
---@field AnimGraphNode_StateResult_13 FAnimNode_StateResult
---@field AnimGraphNode_UseCachedPose_4 FAnimNode_UseCachedPose
---@field AnimGraphNode_StateResult_12 FAnimNode_StateResult
---@field AnimGraphNode_UseCachedPose_3 FAnimNode_UseCachedPose
---@field AnimGraphNode_StateResult_11 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_1 FAnimNode_StateMachine
---@field AnimGraphNode_TransitionResult_17 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_16 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_15 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_14 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_13 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_12 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_UseCachedPose_2 FAnimNode_UseCachedPose
---@field AnimGraphNode_StateResult_10 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_7 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_9 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_6 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_8 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_UseCachedPose_1 FAnimNode_UseCachedPose
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_UseCachedPose FAnimNode_UseCachedPose
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_Root FAnimNode_Root
---@field Direction float
---@field ['Walking?'] boolean
---@field IsWalking boolean
---@field ['isLeftFootUp?'] boolean
---@field PlayEmotion boolean
---@field ['isAngry?'] boolean
---@field ['isHappy?'] boolean
---@field Rotation float
---@field BlinkOffsetBP float
---@field PlayerTransform FTransform
---@field LookAtAlpha float
---@field EyeballsLookat float
---@field ShouldLookAt boolean
---@field HappyFace boolean
---@field AngryFace boolean
---@field ['isDialog?'] boolean
---@field TurnBp float
---@field DialogID int32
---@field DriverSitHeight FVector
---@field RootRotation FRotator
---@field DriverTriggerPos FVector
---@field DirverIdleSnap FVector
---@field ['Female?'] boolean
---@field ['isDisgusted?'] boolean
---@field HappyType int32
---@field AngryType int32
---@field ['WaitingToLong?'] boolean
---@field WaitingAnimTypeBP int32
---@field Speed float
---@field IsRunning boolean
---@field SpawnedBroom AEmployeeBroom_C
---@field CheckLookAtDis boolean
---@field RetargetingAlphaMulti float
---@field SocketPosition FVector
---@field SocketRotation FRotator
---@field NPC_Base AAICharacterBase
---@field isPartyBoy boolean
---@field PartyWalkType0 int32
---@field JumpedFromBus boolean
---@field MovementGroundType EMovementGroundType
---@field bDirtyDialog boolean
---@field bAngryDialog boolean
---@field bHappyDialog boolean
---@field MovementType EMovementType
---@field SpawnedPaintRoller APaintRollerNPC_Bp_C
---@field ['Blend Weights 0'] float
---@field BTurningBP boolean
---@field PlayerLocation FVector
---@field bJog boolean
---@field bRun boolean
---@field bDance1 boolean
---@field bDance2 boolean
---@field bWalk boolean
---@field bIdleTick boolean
---@field bheadScratch boolean
---@field bFaceScratch boolean
---@field bShoulderRub boolean
---@field bneckStrech boolean
---@field bLookAround boolean
---@field bCheckYourSelf boolean
---@field MontageTimer FTimerHandle
---@field NegativeEmotionMontages TArray<TSoftObjectPtr<UAnimMontage>>
---@field PositiveEmotionMontages TArray<TSoftObjectPtr<UAnimMontage>>
---@field bWalkStart boolean
---@field Ground boolean
---@field Vehicle boolean
---@field RetargetingAlpha float
---@field SocketAlpha float
---@field ['In Bone Name'] FName
---@field bPanic boolean
local UNPC_Ai_MasterAnimBp_C = {}

---@param AnimGraph FPoseLink
function UNPC_Ai_MasterAnimBp_C:AnimGraph(AnimGraph) end
function UNPC_Ai_MasterAnimBp_C:HandleMovementType() end
function UNPC_Ai_MasterAnimBp_C:HandleIdles() end
function UNPC_Ai_MasterAnimBp_C:PickGroundMovement() end
---@param DialogID int32
function UNPC_Ai_MasterAnimBp_C:Dialogtype(DialogID) end
---@param NotifyName FName
function UNPC_Ai_MasterAnimBp_C:OnCompleted_C8166F2B454DF1340BB5859E6AD61491(NotifyName) end
---@param NotifyName FName
function UNPC_Ai_MasterAnimBp_C:OnBlendOut_C8166F2B454DF1340BB5859E6AD61491(NotifyName) end
---@param NotifyName FName
function UNPC_Ai_MasterAnimBp_C:OnInterrupted_C8166F2B454DF1340BB5859E6AD61491(NotifyName) end
---@param NotifyName FName
function UNPC_Ai_MasterAnimBp_C:OnNotifyBegin_C8166F2B454DF1340BB5859E6AD61491(NotifyName) end
---@param NotifyName FName
function UNPC_Ai_MasterAnimBp_C:OnNotifyEnd_C8166F2B454DF1340BB5859E6AD61491(NotifyName) end
---@param Loaded UObject
function UNPC_Ai_MasterAnimBp_C:OnLoaded_2A22CEE048AD38367A4B33A53B07B097(Loaded) end
---@param NotifyName FName
function UNPC_Ai_MasterAnimBp_C:OnCompleted_FE4B2BB9456A6FF429ACD5AB6B17AEC2(NotifyName) end
---@param NotifyName FName
function UNPC_Ai_MasterAnimBp_C:OnBlendOut_FE4B2BB9456A6FF429ACD5AB6B17AEC2(NotifyName) end
---@param NotifyName FName
function UNPC_Ai_MasterAnimBp_C:OnInterrupted_FE4B2BB9456A6FF429ACD5AB6B17AEC2(NotifyName) end
---@param NotifyName FName
function UNPC_Ai_MasterAnimBp_C:OnNotifyBegin_FE4B2BB9456A6FF429ACD5AB6B17AEC2(NotifyName) end
---@param NotifyName FName
function UNPC_Ai_MasterAnimBp_C:OnNotifyEnd_FE4B2BB9456A6FF429ACD5AB6B17AEC2(NotifyName) end
---@param Loaded UObject
function UNPC_Ai_MasterAnimBp_C:OnLoaded_874721EC4C6D722CF674BC8DDD102151(Loaded) end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_DespawnBroom() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_SpawnBroom() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_PlayAnimOnBroom() end
function UNPC_Ai_MasterAnimBp_C:CustomEvent() end
function UNPC_Ai_MasterAnimBp_C:CustomEvent_1() end
function UNPC_Ai_MasterAnimBp_C:CustomEvent_2() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_L_foot_up() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_R_foot_up() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_L_LegSFX() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_R_LegSFX() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_BusJumpEnd() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_SpawnPaintRoller() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_DespawnPaintRoller() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_HeadScratchStart() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_FaceScratchStart() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_ShoulderRubStart() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_NeckStretchStart() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_LookaroundStart() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_CheckingYourselfStart() end
---@param DeltaTimeX float
function UNPC_Ai_MasterAnimBp_C:BlueprintUpdateAnimation(DeltaTimeX) end
function UNPC_Ai_MasterAnimBp_C:BlueprintInitializeAnimation() end
---@param DeltaRotation FRotator
function UNPC_Ai_MasterAnimBp_C:CharacterRotationEvent(DeltaRotation) end
---@param ActionID int32
---@param AICharacterBase AAICharacterBase
function UNPC_Ai_MasterAnimBp_C:OnStartActionAnim_Event_0(ActionID, AICharacterBase) end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_WaitingAnimEnd() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_ShouldLookAtOff() end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_ShouldLookAtOn() end
---@param LastSectionName FName
---@param NewSectionName FName
function UNPC_Ai_MasterAnimBp_C:SetMontageNextSection(LastSectionName, NewSectionName) end
function UNPC_Ai_MasterAnimBp_C:IdleVariant() end
function UNPC_Ai_MasterAnimBp_C:CustomEvent_0() end
function UNPC_Ai_MasterAnimBp_C:EndAngryActionAnim() end
function UNPC_Ai_MasterAnimBp_C:EndHappyActionAnim() end
---@param Montage UAnimMontage
---@param bInterrupted boolean
function UNPC_Ai_MasterAnimBp_C:MontageEnded(Montage, bInterrupted) end
function UNPC_Ai_MasterAnimBp_C:AnimNotify_StopPhysicsSim() end
---@param CurrentVehicle AActor
function UNPC_Ai_MasterAnimBp_C:VehicleEnteringFinished(CurrentVehicle) end
---@param EntryPoint int32
function UNPC_Ai_MasterAnimBp_C:ExecuteUbergraph_NPC_Ai_MasterAnimBp(EntryPoint) end


