---@meta

---@class UNPC_NBM_Female_AnimBp_C : UHumanAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_TransitionResult_109 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_108 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_107 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_106 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_105 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_104 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_103 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_102 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_101 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_100 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_99 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_98 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_97 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_96 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_95 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_94 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_93 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_92 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_91 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_90 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_89 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_88 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_87 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_86 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_85 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_84 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_83 FAnimNode_TransitionResult
---@field AnimGraphNode_BlendSpacePlayer_3 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_54 FAnimNode_StateResult
---@field AnimGraphNode_UseCachedPose_13 FAnimNode_UseCachedPose
---@field AnimGraphNode_StateResult_53 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_42 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_52 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_41 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_51 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_40 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_50 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_39 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_49 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_82 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_38 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_48 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_37 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_47 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_36 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_46 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_35 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_45 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_81 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_34 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_44 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_33 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_43 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_32 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_42 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_9 FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose_10 FAnimNode_SaveCachedPose
---@field AnimGraphNode_TransitionResult_80 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_79 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_78 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_77 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_76 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_75 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_74 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_73 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_72 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_71 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_70 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_69 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_68 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_67 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_66 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_65 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_64 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_63 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_31 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_41 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_30 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_40 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_29 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_39 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_28 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_38 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_27 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_37 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_26 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_36 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_2 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_35 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_8 FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose_9 FAnimNode_SaveCachedPose
---@field AnimGraphNode_TransitionResult_62 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_61 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_60 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_59 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_58 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_57 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_25 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_34 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_24 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_33 FAnimNode_StateResult
---@field AnimGraphNode_RandomPlayer FAnimNode_RandomPlayer
---@field AnimGraphNode_StateResult_32 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_7 FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose_8 FAnimNode_SaveCachedPose
---@field AnimGraphNode_TransitionResult_56 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_55 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_54 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_53 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_52 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_51 FAnimNode_TransitionResult
---@field AnimGraphNode_UseCachedPose_12 FAnimNode_UseCachedPose
---@field AnimGraphNode_StateResult_31 FAnimNode_StateResult
---@field AnimGraphNode_Slot_2 FAnimNode_Slot
---@field AnimGraphNode_PoseSnapshot FAnimNode_PoseSnapshot
---@field AnimGraphNode_StateResult_30 FAnimNode_StateResult
---@field AnimGraphNode_ModifyBone FAnimNode_ModifyBone
---@field AnimGraphNode_ComponentToLocalSpace_3 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_LocalToComponentSpace_3 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_SequenceEvaluator_4 FAnimNode_SequenceEvaluator
---@field AnimGraphNode_LocalToComponentSpace_2 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_SequenceEvaluator_3 FAnimNode_SequenceEvaluator
---@field AnimGraphNode_ComponentToLocalSpace_2 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_BlendListByBool FAnimNode_BlendListByBool
---@field AnimGraphNode_TwoBoneIK_1 FAnimNode_TwoBoneIK
---@field AnimGraphNode_TwoBoneIK FAnimNode_TwoBoneIK
---@field AnimGraphNode_StateResult_29 FAnimNode_StateResult
---@field AnimGraphNode_UseCachedPose_11 FAnimNode_UseCachedPose
---@field AnimGraphNode_StateResult_28 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_6 FAnimNode_StateMachine
---@field AnimGraphNode_Slot_1 FAnimNode_Slot
---@field AnimGraphNode_SaveCachedPose_7 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_10 FAnimNode_UseCachedPose
---@field AnimGraphNode_LayeredBoneBlend_3 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_9 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field AnimGraphNode_TransitionResult_50 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_49 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_48 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_47 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_46 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_45 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_44 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_43 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_42 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_41 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_40 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_39 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_38 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_37 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_36 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_35 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_34 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_33 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_32 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_31 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_30 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_29 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_28 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_27 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_26 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_25 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_24 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_23 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_22 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_21 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_20 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_19 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_18 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_17 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_16 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_15 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_14 FAnimNode_TransitionResult
---@field AnimGraphNode_UseCachedPose_8 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_7 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_6 FAnimNode_UseCachedPose
---@field AnimGraphNode_SequencePlayer_23 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByInt_1 FAnimNode_BlendListByInt
---@field AnimGraphNode_StateResult_27 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_1 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_26 FAnimNode_StateResult
---@field AnimGraphNode_UseCachedPose_5 FAnimNode_UseCachedPose
---@field AnimGraphNode_StateResult_25 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_22 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_24 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_21 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_23 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_20 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_22 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_19 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_21 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_13 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_18 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_20 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_17 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_19 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_16 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_18 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_15 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_17 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_12 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_14 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_16 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_13 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_15 FAnimNode_StateResult
---@field AnimGraphNode_UseCachedPose_4 FAnimNode_UseCachedPose
---@field AnimGraphNode_StateResult_14 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_5 FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose_6 FAnimNode_SaveCachedPose
---@field AnimGraphNode_SaveCachedPose_5 FAnimNode_SaveCachedPose
---@field AnimGraphNode_SaveCachedPose_4 FAnimNode_SaveCachedPose
---@field AnimGraphNode_DragonAimSolver FAnimNode_DragonAimSolver
---@field AnimGraphNode_LocalToComponentSpace_1 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace_1 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_BlendListByInt FAnimNode_BlendListByInt
---@field AnimGraphNode_LayeredBoneBlend_2 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_LayeredBoneBlend_1 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_LayeredBoneBlend FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_SequenceEvaluator_2 FAnimNode_SequenceEvaluator
---@field AnimGraphNode_SequenceEvaluator_1 FAnimNode_SequenceEvaluator
---@field AnimGraphNode_SequenceEvaluator FAnimNode_SequenceEvaluator
---@field AnimGraphNode_UseCachedPose_3 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_2 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_1 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose FAnimNode_UseCachedPose
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_12 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_13 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_11 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_12 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_10 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_11 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_9 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_10 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_4 FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose_3 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LegIK_1 FAnimNode_LegIK
---@field AnimGraphNode_ComponentToLocalSpace FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_LocalToComponentSpace FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_LegIK FAnimNode_LegIK
---@field AnimGraphNode_BlendSpacePlayer FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_9 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_3 FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose_2 FAnimNode_SaveCachedPose
---@field AnimGraphNode_SequencePlayer_8 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_8 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_2 FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose_1 FAnimNode_SaveCachedPose
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_7 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_6 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_1 FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose FAnimNode_SaveCachedPose
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field NPC_Base AAICharacterBase
---@field Speed float
---@field MovementGroundType EMovementGroundType
---@field bJog boolean
---@field bDance1 boolean
---@field bDance2 boolean
---@field bRun boolean
---@field bWalk boolean
---@field isPartyBoy boolean
---@field bPanic boolean
---@field DeltaRotation FRotator
---@field CachedRotation FRotator
---@field Rotation float
---@field bTurning_0 boolean
---@field bRabdomIdleDisabled boolean
---@field HandL_IkLoc FVector
---@field HandRIkLoc FVector
---@field MotorbikeMesh USkeletalMeshComponent
---@field ShouldLookAt boolean
---@field CheckLookAtDis boolean
---@field bIdleTick boolean
---@field ['In Bone Name'] FName
---@field SpawnedBroom AEmployeeBroom_C
---@field Vehicle boolean
---@field Ground boolean
---@field MontageTimer FTimerHandle
---@field PositiveEmotionMontages TArray<TSoftObjectPtr<UAnimMontage>>
---@field NegativeEmotionMontages TArray<TSoftObjectPtr<UAnimMontage>>
---@field PlayerLocation FVector
---@field PlayerTransform FTransform
---@field MovementType EMovementType
---@field LookAtAlpha float
---@field IsWalking boolean
---@field Direction float
---@field BLU boolean
---@field SpawnedPaintRoller APaintRollerNPC_Bp_C
---@field RandomIdleTreshold float
---@field bheadScratch boolean
---@field bFaceScratch boolean
---@field bNeckStretch boolean
---@field bShoulderRub boolean
---@field bLookAround boolean
---@field bCheckingThemselves boolean
---@field RandomIdleTimer float
---@field bLeftArmLayerActive boolean
---@field bTickLArmAlpha boolean
---@field CurrentLArmAlphaT float
---@field LeftArmLayerAlphaCurve UCurveFloat
---@field ['In Time to Spawn Mesh'] float
---@field LArmLayerClassToSpawn TSubclassOf<AActor>
---@field LArmLayerSpawnedMesh AActor
---@field LArmLayerSpawnedMeshes TArray<AActor>
---@field bCarEnterFinished boolean
---@field ['Animation Walk Speed Multiplier'] float
---@field bQueueIdle_01 boolean
local UNPC_NBM_Female_AnimBp_C = {}

---@param AnimGraph FPoseLink
function UNPC_NBM_Female_AnimBp_C:AnimGraph(AnimGraph) end
---@param DeltaT float
function UNPC_NBM_Female_AnimBp_C:DestroyLayerSocketSpawnedActorAfterTimer(DeltaT) end
---@param DeltaT float
function UNPC_NBM_Female_AnimBp_C:SpawnLayerSocketActorAfterTimer(DeltaT) end
---@param DeltaT float
function UNPC_NBM_Female_AnimBp_C:HandleLArmAlpha(DeltaT) end
function UNPC_NBM_Female_AnimBp_C:HandleLookAt() end
function UNPC_NBM_Female_AnimBp_C:RollForRandomIdles() end
---@param DeltaT float
function UNPC_NBM_Female_AnimBp_C:RandomIdlesTimer(DeltaT) end
function UNPC_NBM_Female_AnimBp_C:HandleIdles() end
function UNPC_NBM_Female_AnimBp_C:MotorbikeIkHandle() end
function UNPC_NBM_Female_AnimBp_C:HandlePhoneAlpha() end
UNPC_NBM_Female_AnimBp_C['Handle Random Idles'] = function(self, ) end
function UNPC_NBM_Female_AnimBp_C:HandleInPlaceRotation() end
function UNPC_NBM_Female_AnimBp_C:PickGroundMovement() end
---@param NotifyName FName
function UNPC_NBM_Female_AnimBp_C:OnCompleted_1113481C4E62B0F6A692138680A39C6D(NotifyName) end
---@param NotifyName FName
function UNPC_NBM_Female_AnimBp_C:OnBlendOut_1113481C4E62B0F6A692138680A39C6D(NotifyName) end
---@param NotifyName FName
function UNPC_NBM_Female_AnimBp_C:OnInterrupted_1113481C4E62B0F6A692138680A39C6D(NotifyName) end
---@param NotifyName FName
function UNPC_NBM_Female_AnimBp_C:OnNotifyBegin_1113481C4E62B0F6A692138680A39C6D(NotifyName) end
---@param NotifyName FName
function UNPC_NBM_Female_AnimBp_C:OnNotifyEnd_1113481C4E62B0F6A692138680A39C6D(NotifyName) end
---@param Loaded UObject
function UNPC_NBM_Female_AnimBp_C:OnLoaded_A9492E8845C37F66CE30D2906C78B06F(Loaded) end
---@param NotifyName FName
function UNPC_NBM_Female_AnimBp_C:OnCompleted_75E926604E3512437424B08D1009D4C9(NotifyName) end
---@param NotifyName FName
function UNPC_NBM_Female_AnimBp_C:OnBlendOut_75E926604E3512437424B08D1009D4C9(NotifyName) end
---@param NotifyName FName
function UNPC_NBM_Female_AnimBp_C:OnInterrupted_75E926604E3512437424B08D1009D4C9(NotifyName) end
---@param NotifyName FName
function UNPC_NBM_Female_AnimBp_C:OnNotifyBegin_75E926604E3512437424B08D1009D4C9(NotifyName) end
---@param NotifyName FName
function UNPC_NBM_Female_AnimBp_C:OnNotifyEnd_75E926604E3512437424B08D1009D4C9(NotifyName) end
---@param Loaded UObject
function UNPC_NBM_Female_AnimBp_C:OnLoaded_BE98005B4A43D3698FA63C9A9C1D7A2C(Loaded) end
function UNPC_NBM_Female_AnimBp_C:AnimNotify_SpawnBroom() end
function UNPC_NBM_Female_AnimBp_C:AnimNotify_DespawnBroom() end
function UNPC_NBM_Female_AnimBp_C:AnimNotify_SpawnPaintRoller() end
function UNPC_NBM_Female_AnimBp_C:AnimNotify_DespawnPaintRoller() end
function UNPC_NBM_Female_AnimBp_C:AnimNotify_LU_Stop() end
function UNPC_NBM_Female_AnimBp_C:AnimNotify_RU_Stop() end
function UNPC_NBM_Female_AnimBp_C:AnimNotify_RandomIdleTransitionEnd() end
---@param DeltaTimeX float
function UNPC_NBM_Female_AnimBp_C:BlueprintUpdateAnimation(DeltaTimeX) end
function UNPC_NBM_Female_AnimBp_C:BlueprintInitializeAnimation() end
---@param DeltaRotation FRotator
function UNPC_NBM_Female_AnimBp_C:CharacterRotationEvent(DeltaRotation) end
---@param ActionID int32
---@param AICharacterBase AAICharacterBase
function UNPC_NBM_Female_AnimBp_C:OnStartActionAnim_Event_0(ActionID, AICharacterBase) end
function UNPC_NBM_Female_AnimBp_C:AnimNotify_ShouldLookAtOff() end
function UNPC_NBM_Female_AnimBp_C:AnimNotify_ShouldLookAtOn() end
---@param LastSectionName FName
---@param NewSectionName FName
function UNPC_NBM_Female_AnimBp_C:SetMontageNextSection(LastSectionName, NewSectionName) end
function UNPC_NBM_Female_AnimBp_C:EndAngryActionAnim() end
function UNPC_NBM_Female_AnimBp_C:EndHappyActionAnim() end
---@param Montage UAnimMontage
---@param bInterrupted boolean
function UNPC_NBM_Female_AnimBp_C:MontageEnded(Montage, bInterrupted) end
function UNPC_NBM_Female_AnimBp_C:IdleVariant() end
---@param CurrentVehicle AActor
function UNPC_NBM_Female_AnimBp_C:VehicleEnteringFinished(CurrentVehicle) end
function UNPC_NBM_Female_AnimBp_C:AnimNotify_PhoneSheathingEnd() end
function UNPC_NBM_Female_AnimBp_C:AnimNotify_StopPhysicsSimulation() end
---@param Montage UAnimMontage
function UNPC_NBM_Female_AnimBp_C:OnMontageStarted_Event_0(Montage) end
---@param bActive boolean
---@param Pose UAnimSequence
---@param ActorToSpawn TSubclassOf<AActor>
---@param InTimeToSpawnMesh float
function UNPC_NBM_Female_AnimBp_C:OnLeftArmLayerStateChange(bActive, Pose, ActorToSpawn, InTimeToSpawnMesh) end
---@param Montage UAnimMontage
---@param bInterrupted boolean
function UNPC_NBM_Female_AnimBp_C:CarLeavingMontageEnd(Montage, bInterrupted) end
---@param Pose UAnimSequence
---@param bSpawnActor boolean
---@param ActorToSpawn TSubclassOf<AActor>
---@param PartToActivate FGameplayTag
---@param InTimeToSpawnMesh float
---@param BlendTime float
function UNPC_NBM_Female_AnimBp_C:OnHandsLayerStateChange(Pose, bSpawnActor, ActorToSpawn, PartToActivate, InTimeToSpawnMesh, BlendTime) end
---@param InTimeToDestroyMesh float
---@param BlendOutTime float
function UNPC_NBM_Female_AnimBp_C:DeactivateHandsLayer(InTimeToDestroyMesh, BlendOutTime) end
function UNPC_NBM_Female_AnimBp_C:StopHandsLayerForMontage() end
function UNPC_NBM_Female_AnimBp_C:ActivateRandomQueueIdlePose() end
function UNPC_NBM_Female_AnimBp_C:DeactivateRandomQueueIdlePose() end
function UNPC_NBM_Female_AnimBp_C:AnimNotify_ExitVariantIdles() end
---@param EntryPoint int32
function UNPC_NBM_Female_AnimBp_C:ExecuteUbergraph_NPC_NBM_Female_AnimBp(EntryPoint) end


