---@meta

---@class UP_PC_Warehouse_C : UPcBaseTab
---@field UberGraphFrame FPointerToUberGraphFrame
---@field MoneyPopup UWidgetAnimation
---@field Vibe UWidgetAnimation
---@field AlcocholFilter UFilterButton_C
---@field AllFilter UFilterButton_C
---@field BG_IMG UImage
---@field CapacityIcon UImage
---@field CarCareFilter UFilterButton_C
---@field CigaretesFilter UFilterButton_C
---@field DrinksFilter UFilterButton_C
---@field ExitButton UDragoButton
---@field FuelAmmountTXT UTextBlock
---@field GlassesFilter UFilterButton_C
---@field GrayButtonBlocker UImage
---@field GreenBottomLine UImage
---@field HatsFilter UFilterButton_C
---@field IceCreamsFilter UFilterButton_C
---@field Image_74 UImage
---@field Image_222 UImage
---@field LevelUpButton UDragoButton
---@field LevelUpTXT UTextBlock
---@field MaxLevelTXT UTextBlock
---@field MoneyBox UOverlay
---@field MoreInfoWerehouseTXT UTextBlock
---@field NewsPapersFilter UFilterButton_C
---@field PasteriesFilter UFilterButton_C
---@field PC_PS4_bindings UPC_PS4_bindings_C
---@field PlayerMoneytTXT UTextBlock
---@field PlayerMoneytTXT_1 UTextBlock
---@field RepaintButton UDragoButton
---@field ReqTXT UTextBlock
---@field SnacksFilter UFilterButton_C
---@field SoftToysFilter UFilterButton_C
---@field StructureIllustration UImage
---@field Tidal_StructureIlustration UImage
---@field ToLeftButton UButton
---@field ToLeftButton_1 UButton
---@field ToysFilter UFilterButton_C
---@field UpgradeWarehouseCostTXT UTextBlock
---@field UpgradeWarehouseCostTXT_1 UTextBlock
---@field WareHouseCapacityTXT UTextBlock
---@field WarehouseLevel UTextBlock
---@field WareHouseProductsScroll UScrollBox
---@field WBP_KeyHint_LeftShoulder UWBP_KeyHint_C
---@field WBP_KeyHint_MoveLeft UWBP_KeyHint_C
---@field WBP_KeyHint_MoveLeft_1 UWBP_KeyHint_C
---@field WBP_KeyHint_RightButton UWBP_KeyHint_C
---@field QuestForUpgradeDone boolean
---@field CanUpgradeAtStationLevel boolean
---@field CanPayUpgradeMoeny boolean
---@field MiddleSegmentElements TArray<UDragoButton>
---@field keySelected1 int32
---@field CanBePayedUpgradeTree boolean
---@field ShelfItemsAmmount int32
---@field SelectedCategories TArray<EItemTypeCategory>
---@field FiltersOn int32
---@field CurrentIndex int32
---@field FilterButtons TArray<UFilterButton_C>
---@field GamePadFilterIndex int32
---@field GamePadSection int32
---@field GamePadItemIndex int32
local UP_PC_Warehouse_C = {}

---@param MyGeometry FGeometry
---@param InKeyEvent FKeyEvent
---@return FEventReply
function UP_PC_Warehouse_C:OnPreviewKeyDown(MyGeometry, InKeyEvent) end
---@param Visible boolean
function UP_PC_Warehouse_C:HintsVisibility(Visible) end
function UP_PC_Warehouse_C:HnadleAllOffOn() end
---@param Category EItemTypeCategory
function UP_PC_Warehouse_C:AddRemoveCategory(Category) end
function UP_PC_Warehouse_C:AchievementHandling() end
---@param Level FName
function UP_PC_Warehouse_C:PayForWarehouse(Level) end
UP_PC_Warehouse_C['Set Hovered'] = function(self, ) end
function UP_PC_Warehouse_C:decrementsFilters() end
function UP_PC_Warehouse_C:incrementsFilter() end
---@param StationLevel int32
---@param UpgradeCoast float
---@param QuestToComplite TSubclassOf<UGSSQuest>
---@param CanBePayed boolean
---@param CanPay boolean
---@param HaveStationLevel boolean
function UP_PC_Warehouse_C:PayForUpgrade(StationLevel, UpgradeCoast, QuestToComplite, CanBePayed, CanPay, HaveStationLevel) end
function UP_PC_Warehouse_C:SetFilterProduct() end
---@param KeyEvent FKeyEvent
function UP_PC_Warehouse_C:TopMenuHandle(KeyEvent) end
function UP_PC_Warehouse_C:BndEvt__DragoButton_8_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature() end
function UP_PC_Warehouse_C:Construct() end
function UP_PC_Warehouse_C:BndEvt__LevelUpButton_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature() end
function UP_PC_Warehouse_C:InitGamePad() end
function UP_PC_Warehouse_C:PressGLT() end
function UP_PC_Warehouse_C:PressGRT() end
function UP_PC_Warehouse_C:PressLT() end
function UP_PC_Warehouse_C:CustomEvent() end
function UP_PC_Warehouse_C:Destruct() end
function UP_PC_Warehouse_C:BndEvt__ExitButton_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature() end
---@param CharacterMoney float
---@param Difference float
---@param YieldType EEconomyDetailedYieldType
function UP_PC_Warehouse_C:UpdateMoneyAmmount(CharacterMoney, Difference, YieldType) end
function UP_PC_Warehouse_C:RefreshForGamePad() end
---@param CurrentFuelAmount float
function UP_PC_Warehouse_C:UpdateFuel(CurrentFuelAmount) end
function UP_PC_Warehouse_C:BndEvt__ExitButton_K2Node_ComponentBoundEvent_13_OnButtonHoverEvent__DelegateSignature() end
function UP_PC_Warehouse_C:BndEvt__ExitButton_K2Node_ComponentBoundEvent_17_OnButtonHoverEvent__DelegateSignature() end
---@param Inventory UInventoryComponent
function UP_PC_Warehouse_C:Refresh(Inventory) end
function UP_PC_Warehouse_C:RefreshOnInventoryUpdate() end
function UP_PC_Warehouse_C:WareHouseLVLupFromUpgradeTree() end
function UP_PC_Warehouse_C:RefreshOnInventoryCap() end
function UP_PC_Warehouse_C:BindFilters() end
function UP_PC_Warehouse_C:OnClickedIceCreamFilter() end
function UP_PC_Warehouse_C:OnClickedSoftDrinksFilter() end
function UP_PC_Warehouse_C:OnClickedFilterFood() end
function UP_PC_Warehouse_C:OnClickedAlcohol() end
function UP_PC_Warehouse_C:OnClickedCigaretesFilter() end
function UP_PC_Warehouse_C:OnClickedCarCareFilter() end
function UP_PC_Warehouse_C:OnClickedNewsPapersFilter() end
function UP_PC_Warehouse_C:OnClickedHatsFilter() end
function UP_PC_Warehouse_C:OnClickedGlassesFilter() end
function UP_PC_Warehouse_C:OnClickedSoftToysFilter() end
function UP_PC_Warehouse_C:OnClickedToysFilter() end
function UP_PC_Warehouse_C:OnClickedPasteriesFilter() end
function UP_PC_Warehouse_C:OnClickedAllFilters() end
function UP_PC_Warehouse_C:RefreshJustCap() end
function UP_PC_Warehouse_C:CustomEscape() end
---@param IsDesignTime boolean
function UP_PC_Warehouse_C:PreConstruct(IsDesignTime) end
---@param Increase boolean
function UP_PC_Warehouse_C:GamePadHoverNextFilter(Increase) end
---@param Increase boolean
function UP_PC_Warehouse_C:GamePadHoverNextItem(Increase) end
---@param Increase boolean
function UP_PC_Warehouse_C:GamePadSwitchItemButton(Increase) end
function UP_PC_Warehouse_C:GamePadItemButtonClick() end
function UP_PC_Warehouse_C:GamePadFilterClick() end
function UP_PC_Warehouse_C:GamePadLevelUpButton() end
---@param EntryPoint int32
function UP_PC_Warehouse_C:ExecuteUbergraph_P_PC_Warehouse(EntryPoint) end


