---@meta

---@class APlayerCharacter_BP_C : AGSSPlayerCharacter
---@field UberGraphFrame FPointerToUberGraphFrame
---@field PhotoModeComponent UBPC_PhotoMode_C
---@field BP_TechTreeManager UBP_TechTreeManager_C
---@field WidgetInteraction UWidgetInteractionComponent
---@field CinematicCamera UCineCameraComponent
---@field Player_AnimationManager UPlayer_AnimationManager_C
---@field Timeline_0_Width_272F6C3C41C494CB0ABAB3AD06FA0270 float
---@field Timeline_0_Height_272F6C3C41C494CB0ABAB3AD06FA0270 float
---@field Timeline_0__Direction_272F6C3C41C494CB0ABAB3AD06FA0270 ETimelineDirection::Type
---@field Timeline_0 UTimelineComponent
---@field Timeline_1_Width_64FC509D429FEF1C807964A5255EDFCD float
---@field Timeline_1_Height_64FC509D429FEF1C807964A5255EDFCD float
---@field Timeline_1__Direction_64FC509D429FEF1C807964A5255EDFCD ETimelineDirection::Type
---@field Timeline_1 UTimelineComponent
---@field Timeline_3_Time_A834B3A44E8027F4B9943C88F3E99DE5 float
---@field Timeline_3__Direction_A834B3A44E8027F4B9943C88F3E99DE5 ETimelineDirection::Type
---@field Timeline_3 UTimelineComponent
---@field SetPlayerPosition_Time_449C712C4486D0F20DD3198116902741 float
---@field SetPlayerPosition__Direction_449C712C4486D0F20DD3198116902741 ETimelineDirection::Type
---@field SetPlayerPosition UTimelineComponent
---@field DisplayedActorOnStartRPM AActor
---@field StopPositioning boolean
---@field EconomyDebugUI_Ref UEconomyDebug_UI_WBP_C
---@field StatDebugUI_Ref UStatDebug_UI_WBP_C
---@field EventDebugUI_Ref UDebugEvents_UI_WBP_C
---@field CarWashDebugUI_Ref UCarWashDebug_WBP_C
---@field PauseMenuRef UUserWidget
---@field CurInventory_0 UInventoryComponent
---@field RotateRight boolean
---@field RotationCurrentValue float
---@field RotateLeft boolean
---@field RotateValue float
---@field ShiftPressed boolean
---@field RotationSpeed float
---@field IsInAction boolean
---@field ToolState ECircularMenuChoice
---@field RocketJumpAirControlTimer FTimerHandle
---@field DefaultAirControl float
---@field DisplayedComponent_0 UPrimitiveComponent
---@field InventoryWidgetClass TSoftClassPtr<UUserWidget>
---@field HidenWidgets TMap<UUserWidget, ESlateVisibility>
---@field bWidgetsWasHide boolean
---@field ActualCineCameraActor ACineCameraActor
---@field IsShowingDebugCameras boolean
---@field DebugCamerasWidget UUserWidget
local APlayerCharacter_BP_C = {}

function APlayerCharacter_BP_C:OnValidatorInteractionEnd() end
---@param Key FKey
---@param OpenCase FString
function APlayerCharacter_BP_C:OpenPhotoMode(Key, OpenCase) end
---@param Actor AActor
---@param Used boolean
APlayerCharacter_BP_C['SD Try To Use Item On Human Base'] = function(self, Actor, Used) end
---@param IsInMiniGame boolean
function APlayerCharacter_BP_C:GetIsPlayerInWrenchMiniGame(IsInMiniGame) end
---@param Right boolean
---@param Left boolean
---@param PlaceableActor APlaceableActor
---@return float
function APlayerCharacter_BP_C:GetRotationValue(Right, Left, PlaceableActor) end
---@param EventName FName
APlayerCharacter_BP_C['Set Event to Start'] = function(self, EventName) end
---@param HitResults TArray<FHitResult>
---@param ClassToLookFor TSubclassOf<AActor>
---@param ComponentClass TSubclassOf<UPrimitiveComponent>
---@param bHit boolean
---@param ProductRef AActor
---@param ComponentRef UPrimitiveComponent
function APlayerCharacter_BP_C:HitContainsT_NoObstacleCheck(HitResults, ClassToLookFor, ComponentClass, bHit, ProductRef, ComponentRef) end
---@param Hit boolean
---@param HitActor AActor
---@param HitComponent UPrimitiveComponent
---@param HitResult FHitResult
function APlayerCharacter_BP_C:PlayerTraceLine(Hit, HitActor, HitComponent, HitResult) end
---@param HitResults TArray<FHitResult>
---@param ClassToLookFor TSubclassOf<AActor>
---@param bHit boolean
---@param ProductRef AActor
---@param ComponentRef UPrimitiveComponent
function APlayerCharacter_BP_C:HitContainsT_FindLast(HitResults, ClassToLookFor, bHit, ProductRef, ComponentRef) end
---@param HitResults TArray<FHitResult>
---@param ClassToLookFor TSubclassOf<AActor>
---@param bHit boolean
---@param ProductRef AActor
---@param ComponentRef UPrimitiveComponent
function APlayerCharacter_BP_C:HitContainsT(HitResults, ClassToLookFor, bHit, ProductRef, ComponentRef) end
APlayerCharacter_BP_C['Handle Opening Of Tool Menu Old'] = function(self, ) end
---@param ToolChoice ECircularMenuChoice
APlayerCharacter_BP_C['Spawn Tool Old'] = function(self, ToolChoice) end
function APlayerCharacter_BP_C:UserConstructionScript() end
function APlayerCharacter_BP_C:SetPlayerPosition__FinishedFunc() end
function APlayerCharacter_BP_C:SetPlayerPosition__UpdateFunc() end
function APlayerCharacter_BP_C:Timeline_3__FinishedFunc() end
function APlayerCharacter_BP_C:Timeline_3__UpdateFunc() end
function APlayerCharacter_BP_C:Timeline_0__FinishedFunc() end
function APlayerCharacter_BP_C:Timeline_0__UpdateFunc() end
function APlayerCharacter_BP_C:Timeline_1__FinishedFunc() end
function APlayerCharacter_BP_C:Timeline_1__UpdateFunc() end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_RotateRight_K2Node_InputActionEvent_25(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_RotateRight_K2Node_InputActionEvent_24(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_RotateLeft_K2Node_InputActionEvent_23(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_RotateLeft_K2Node_InputActionEvent_22(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_RPM_K2Node_InputActionEvent_21(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_RPM_K2Node_InputActionEvent_20(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_LPM_K2Node_InputActionEvent_19(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_LPM_K2Node_InputActionEvent_18(Key) end
---@param NotifyName FName
function APlayerCharacter_BP_C:OnNotifyEnd_94EB3C26469CDABB116B6E955B067B77(NotifyName) end
---@param NotifyName FName
function APlayerCharacter_BP_C:OnNotifyBegin_94EB3C26469CDABB116B6E955B067B77(NotifyName) end
---@param NotifyName FName
function APlayerCharacter_BP_C:OnInterrupted_94EB3C26469CDABB116B6E955B067B77(NotifyName) end
---@param NotifyName FName
function APlayerCharacter_BP_C:OnBlendOut_94EB3C26469CDABB116B6E955B067B77(NotifyName) end
---@param NotifyName FName
function APlayerCharacter_BP_C:OnCompleted_94EB3C26469CDABB116B6E955B067B77(NotifyName) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_Interaction_F_K2Node_InputActionEvent_17(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_Zero_K2Node_InputKeyEvent_12(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_One_K2Node_InputKeyEvent_11(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_Three_K2Node_InputKeyEvent_10(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_ChangeInventoryDown_K2Node_InputActionEvent_16(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_ChangeInventoryUp_K2Node_InputActionEvent_15(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_Minigame_SpecialAction_01_K2Node_InputActionEvent_14(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_Minigame_SpecialAction_01_K2Node_InputActionEvent_13(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_Escape_K2Node_InputActionEvent_12(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_LPM_K2Node_InputActionEvent_11(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_LPM_K2Node_InputActionEvent_10(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_RotateSpeedIncrease_K2Node_InputActionEvent_9(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_RotateSpeedIncrease_K2Node_InputActionEvent_8(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_Nine_K2Node_InputKeyEvent_9(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_F9_K2Node_InputKeyEvent_8(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_F5_K2Node_InputKeyEvent_7(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_DecreaseSnapRotation_K2Node_InputActionEvent_7(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_IncreaseSnapRotation_K2Node_InputActionEvent_6(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_DecreaseSnapDistance_K2Node_InputActionEvent_5(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_IncreaseSnapDistance_K2Node_InputActionEvent_4(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_Two_K2Node_InputKeyEvent_6(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_NumPadZero_K2Node_InputKeyEvent_5(Key) end
---@param Loaded UClass
function APlayerCharacter_BP_C:OnLoaded_2A391F504EDAD2C074143B92BD56A5F1(Loaded) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_Four_K2Node_InputKeyEvent_4(Key) end
---@param Key FKey
APlayerCharacter_BP_C['InpActEvt_Ctrl+Alt+Shift_B_K2Node_InputKeyEvent_3'] = function(self, Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_OpenPhotoMode_K2Node_InputActionEvent_3(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_Help_K2Node_InputActionEvent_2(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_ReportBug_K2Node_InputActionEvent_1(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_Seven_K2Node_InputKeyEvent_2(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_NumPadFive_K2Node_InputKeyEvent_1(Key) end
---@param Loaded UClass
function APlayerCharacter_BP_C:OnLoaded_1AA1862C4990DC0B26E3C080AAF5DDC0(Loaded) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_HideUI_K2Node_InputActionEvent_0(Key) end
---@param Key FKey
function APlayerCharacter_BP_C:InpActEvt_Eight_K2Node_InputKeyEvent_0(Key) end
function APlayerCharacter_BP_C:Interacted_Minigame() end
function APlayerCharacter_BP_C:Interacted_PC() end
function APlayerCharacter_BP_C:ReceiveBeginPlay() end
---@param DeltaSeconds float
function APlayerCharacter_BP_C:ReceiveTick(DeltaSeconds) end
function APlayerCharacter_BP_C:StopOutline() end
function APlayerCharacter_BP_C:ForceTraceLine() end
function APlayerCharacter_BP_C:ExitMapEvent() end
---@param AxisValue float
function APlayerCharacter_BP_C:InpAxisEvt_TurnRate_K2Node_InputAxisEvent_38(AxisValue) end
---@param AxisValue float
function APlayerCharacter_BP_C:InpAxisEvt_LookUpRate_K2Node_InputAxisEvent_53(AxisValue) end
function APlayerCharacter_BP_C:PositionPlayer() end
function APlayerCharacter_BP_C:PrologWakeUpEvent() end
---@param ToolNumber int32
function APlayerCharacter_BP_C:ToolSelection(ToolNumber) end
---@param Employee AEmployee_Base_C
---@param FromPC boolean
function APlayerCharacter_BP_C:TalkWithEmployee(Employee, FromPC) end
function APlayerCharacter_BP_C:ToggleEconomyDebug() end
function APlayerCharacter_BP_C:ToggleStatDebug() end
function APlayerCharacter_BP_C:ForceOutline() end
---@param ToolChoice ECircularMenuChoice
function APlayerCharacter_BP_C:SpawnTool(ToolChoice) end
function APlayerCharacter_BP_C:HandleOpeningOfToolMenu() end
---@param ActorTarget AActor
---@param PositionToLookAt FVector
function APlayerCharacter_BP_C:RotatePlayerToActorOrLocation(ActorTarget, PositionToLookAt) end
function APlayerCharacter_BP_C:ToggleEventDebug() end
function APlayerCharacter_BP_C:ToggleCarWashDebug() end
---@param EventName FName
function APlayerCharacter_BP_C:TriggerEvent(EventName) end
function APlayerCharacter_BP_C:OnEscapeClicked() end
---@param ExplosionLocation FVector
---@param HitActor AActor
function APlayerCharacter_BP_C:OnCannonExplosion(ExplosionLocation, HitActor) end
---@param Hit FHitResult
function APlayerCharacter_BP_C:OnLanded(Hit) end
function APlayerCharacter_BP_C:OnAirControlExpired() end
function APlayerCharacter_BP_C:OnStepIntoLava() end
---@param InputTicketState eTicketState
---@param TargetNPC AAICharacterBase
function APlayerCharacter_BP_C:StartCinemaInteraction(InputTicketState, TargetNPC) end
function APlayerCharacter_BP_C:EndCinemaInteraction() end
function APlayerCharacter_BP_C:Action_LPM_Pressed() end
function APlayerCharacter_BP_C:Action_LPM_Released() end
function APlayerCharacter_BP_C:Action_RPM_Pressed() end
function APlayerCharacter_BP_C:Action_RPM_Released() end
function APlayerCharacter_BP_C:CustomOpenPhotoMode() end
function APlayerCharacter_BP_C:HideWholeUI() end
---@param PC APlayerController
function APlayerCharacter_BP_C:K2_OnBecomeViewTarget(PC) end
---@param PC APlayerController
function APlayerCharacter_BP_C:K2_OnEndViewTarget(PC) end
---@param Hours int32
function APlayerCharacter_BP_C:SetJoeCrashTime(Hours) end
---@param IsHudHidden boolean
function APlayerCharacter_BP_C:SetHudVisibilityWithOptions(IsHudHidden) end
---@param bShowRedDot boolean
function APlayerCharacter_BP_C:EnableWidgetInteractionDebugDot(bShowRedDot) end
function APlayerCharacter_BP_C:SetDefaultWidgetInteraction() end
function APlayerCharacter_BP_C:SetMouseWidgetInteraction() end
function APlayerCharacter_BP_C:ActivateCinematicCamera() end
function APlayerCharacter_BP_C:DeactivateCinematicCamera() end
---@param EntryPoint int32
function APlayerCharacter_BP_C:ExecuteUbergraph_PlayerCharacter_BP(EntryPoint) end


