---@meta

---@class UWBP_ScheduleEmployee_C : UGSSBaseWidget
---@field UberGraphFrame FPointerToUberGraphFrame
---@field HoverInfo UWidgetAnimation
---@field HoverHiddenInfo UWidgetAnimation
---@field ShowInfo UWidgetAnimation
---@field NotPaidAnim UWidgetAnimation
---@field HoverAnim UWidgetAnimation
---@field AutoPay_CheckBox UCheckBox
---@field BG_Image UImage
---@field BG_Image_1 UImage
---@field BG_Image_2 UImage
---@field BonusTimerTXT UTextBlock
---@field Button_info UButton
---@field CostPerCashTXT UTextBlock
---@field CostPerCleaningTXT UTextBlock
---@field CostPerFuelTXT UTextBlock
---@field CostPerIceCreamsTXT UTextBlock
---@field CostPerRepairTXT UTextBlock
---@field CostPerRestock UTextBlock
---@field DayNightAlert_Button UButton
---@field DayNightShift_Overlay UOverlay
---@field Employee_Avatar_IMG UImage
---@field Employee_Name_TXT UTextBlock
---@field Employee_Name_TXT_1 UTextBlock
---@field EnergyRadialProgress UImage
---@field EnergyRadialProgress_1 UImage
---@field FireEmployee_Button UButton
---@field FirstCheckBoxBlocker_IMG UImage
---@field FirstJob_CheckBox UCheckBox
---@field FirstJob_Picker UComboBoxString
---@field GamePadAutoPayCheckBox_IMG UImage
---@field GamePadFireEmployee_IMG UImage
---@field GamePadFirstCheckBox_IMG UImage
---@field GamePadFirstJobPicker_IMG UImage
---@field GamePadRestartEmployee_IMG UImage
---@field GamePadSecondCheckBox_IMG UImage
---@field GamePadSecondJobPicker_IMG UImage
---@field GamePadShiftPicker_IMG UImage
---@field Image UImage
---@field Image_1 UImage
---@field Image_65 UImage
---@field Image_68 UImage
---@field Image_141 UImage
---@field Image_144 UImage
---@field Image_208 UImage
---@field Image_day UImage
---@field Image_night UImage
---@field Job_Sizer USizeBox
---@field MoreInfo_ScrollBox UScrollBox
---@field MoreInfoContent_Horizontal UHorizontalBox
---@field neumorph_button_1 Uneumorph_button_C
---@field neumorph_button_premium Uneumorph_button_C
---@field NPC_ICON UImage
---@field Overlay_Info UOverlay
---@field Overlay_resting UOverlay
---@field Pay_Image UImage
---@field Premium_TXT UTextBlock
---@field ProgressBar_46 UProgressBar
---@field ProgressBar_cash UProgressBar
---@field ProgressBar_cleaning UProgressBar
---@field ProgressBar_fueling UProgressBar
---@field ProgressBar_ice_cream UProgressBar
---@field ProgressBar_repair UProgressBar
---@field ProgressBar_Restocking UProgressBar
---@field ResetEmployee_Button UButton
---@field Resting_Image UImage
---@field RetainerBox_0 URetainerBox
---@field SalaryFirstTask_TXT UTextBlock
---@field SalarySecondTask_TXT UTextBlock
---@field SecondCheckBoxBlocker_IMG UImage
---@field SecondJob_CheckBox UCheckBox
---@field SecondJob_Picker UComboBoxString
---@field SetAirCompressorLevelTXT UTextBlock
---@field SetCarRepairLevelTXT UTextBlock
---@field SetCashRegisterLevelTXT UTextBlock
---@field SetCleaningLevelTXT UTextBlock
---@field SetDescriptionTXT UTextBlock
---@field SetFuelingLevelTXT UTextBlock
---@field SetIceCreamsLevelTXT UTextBlock
---@field SetRestockingLevel UTextBlock
---@field Shif_houer_TXT UTextBlock
---@field Shift_Picker UComboBoxString
---@field SizeBox_Paid USizeBox
---@field TimerOverlay UOverlay
---@field TotalMoneyEarned_TXT UTextBlock
---@field VerticalBox_0 UVerticalBox
---@field WidgetSwitcher_0 UWidgetSwitcher
---@field AICharacterBase AAICharacterBase
---@field FirstJobPicked EEmployeeTask
---@field JobsArray TArray<FText>
---@field IndexToEnum TMap<int32, EEmployeeSkill>
---@field SecondJobPicked EEmployeeTask
---@field OptionAccept UWBP_OptionAccept_C
---@field Employee UEmployeeShift
---@field FirstPickedTaskName FString
---@field SecondPickedTaskName FString
---@field bIsInfoHidden boolean
---@field CreatedInDialogue boolean
---@field WBP_OwnedEmploye_REF UWBP_OwnedEmployee_C
---@field TaskNameToEnumx TArray<FS_JobsLocalization>
---@field FirstJobArrayIndex int32
---@field SecondJobArrayIndex int32
---@field DayNightLocalization TArray<FText>
---@field TaskOnConstruct FText
---@field UpdatedTask FText
---@field bLock boolean
---@field AllWidgetsOfKind TArray<UWBP_ScheduleEmployee_C>
---@field IndexToWidget TMap<int32, UWidget>
---@field SelectedItemFirstJob FString
---@field SelectedItemSecondJob FString
---@field FirstJobChecked boolean
---@field SecondJobChecked boolean
---@field GamePadCurrentButton int32
---@field AutoPayChecked boolean
---@field GamePadFirstJobOption int32
local UWBP_ScheduleEmployee_C = {}

---@param Cost UTextBlock
---@param ProgressBar UProgressBar
---@param Level UTextBlock
---@param Employee AAICharacterBase
---@param EmployeeSkill FEmployeeSkill
function UWBP_ScheduleEmployee_C:UpdateSkillLevels(Cost, ProgressBar, Level, Employee, EmployeeSkill) end
function UWBP_ScheduleEmployee_C:SetCorrectTimeConvention() end
function UWBP_ScheduleEmployee_C:GamePadSetupElements() end
---@param IndextoCheck int32
---@param Enabled boolean
function UWBP_ScheduleEmployee_C:GamePadCheckIsEnabled(IndextoCheck, Enabled) end
---@param Item FString
function UWBP_ScheduleEmployee_C:On_FirstJob_Picker_GenerateWidget_0(Item) end
UWBP_ScheduleEmployee_C['Update Levels and Skills'] = function(self, ) end
function UWBP_ScheduleEmployee_C:SetShiftVisuals() end
function UWBP_ScheduleEmployee_C:SetAvailableOptions() end
---@param TaskPickerToChange UComboBoxString
---@param Task FString
---@param ChangedPickerSetTask FString
function UWBP_ScheduleEmployee_C:RemoveAvailableTask(TaskPickerToChange, Task, ChangedPickerSetTask) end
---@param TaskPriority int32
function UWBP_ScheduleEmployee_C:SetAssignedTasksInfo(TaskPriority) end
function UWBP_ScheduleEmployee_C:Construct() end
---@param SelectedItem FString
---@param SelectionType ESelectInfo::Type
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_FirstJob_Picker_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature(SelectedItem, SelectionType) end
---@param SelectedItem FString
---@param SelectionType ESelectInfo::Type
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_SecondJob_Picker_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature(SelectedItem, SelectionType) end
function UWBP_ScheduleEmployee_C:OnClickedYes() end
function UWBP_ScheduleEmployee_C:OnClickedNo() end
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_FireEmployee_Button_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature() end
---@param UpdatedTime FTimeStruct
function UWBP_ScheduleEmployee_C:UpdateInfo(UpdatedTime) end
---@param SelectedItem FString
---@param SelectionType ESelectInfo::Type
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_Shift_Picker_K2Node_ComponentBoundEvent_7_OnSelectionChangedEvent__DelegateSignature(SelectedItem, SelectionType) end
---@param bIsChecked boolean
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_SecondJob_CheckBox_K2Node_ComponentBoundEvent_1_OnCheckBoxComponentStateChanged__DelegateSignature(bIsChecked) end
---@param bIsChecked boolean
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_FirstJob_CheckBox_K2Node_ComponentBoundEvent_3_OnCheckBoxComponentStateChanged__DelegateSignature(bIsChecked) end
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_Shift_Picker_K2Node_ComponentBoundEvent_6_OnOpeningEvent__DelegateSignature() end
---@param bIsChecked boolean
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_AutoPay_CheckBox_K2Node_ComponentBoundEvent_9_OnCheckBoxComponentStateChanged__DelegateSignature(bIsChecked) end
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_neumorph_button_K2Node_ComponentBoundEvent_8_ButtonClicked__DelegateSignature() end
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_neumorph_button_1_K2Node_ComponentBoundEvent_11_ButtonClicked__DelegateSignature() end
---@param MyGeometry FGeometry
---@param MouseEvent FPointerEvent
function UWBP_ScheduleEmployee_C:OnMouseEnter(MyGeometry, MouseEvent) end
---@param MouseEvent FPointerEvent
function UWBP_ScheduleEmployee_C:OnMouseLeave(MouseEvent) end
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_Button_info_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature() end
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_Button_info_K2Node_ComponentBoundEvent_10_OnButtonHoverEvent__DelegateSignature() end
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_Button_info_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature() end
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_FireEmployee_Button_1_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature() end
function UWBP_ScheduleEmployee_C:Destruct() end
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_FirstJob_Picker_K2Node_ComponentBoundEvent_14_OnOpeningEvent__DelegateSignature() end
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_SecondJob_Picker_K2Node_ComponentBoundEvent_15_OnOpeningEvent__DelegateSignature() end
UWBP_ScheduleEmployee_C['Enabled First CheckBox'] = function(self, ) end
UWBP_ScheduleEmployee_C['Enable Second CheckBox'] = function(self, ) end
---@param StartedTask UTaskBase
function UWBP_ScheduleEmployee_C:RefreshShiftVisuals(StartedTask) end
function UWBP_ScheduleEmployee_C:RefreshVisualsAfterPay() end
function UWBP_ScheduleEmployee_C:BndEvt__WBP_ScheduleEmployee_Button_146_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature() end
function UWBP_ScheduleEmployee_C:ForceHiden() end
function UWBP_ScheduleEmployee_C:GamePadSelectionChangedShift() end
---@param SelectedItem FString
function UWBP_ScheduleEmployee_C:GamePadSelectionChangedFirstJob(SelectedItem) end
---@param SelectedItem FString
function UWBP_ScheduleEmployee_C:GamePadSelectionChangedSecondJob(SelectedItem) end
function UWBP_ScheduleEmployee_C:GamePadFireEmployee() end
function UWBP_ScheduleEmployee_C:GamePadFireEmployeeClickNo() end
function UWBP_ScheduleEmployee_C:GamePadFireEmployeeClickYes() end
function UWBP_ScheduleEmployee_C:GamePadClickPremium() end
function UWBP_ScheduleEmployee_C:GamePadPaySallary() end
function UWBP_ScheduleEmployee_C:GamePadCheckFirstJob() end
function UWBP_ScheduleEmployee_C:GamePadCheckSecondJob() end
---@param Hover boolean
function UWBP_ScheduleEmployee_C:GamePadHoverMoreInfo(Hover) end
function UWBP_ScheduleEmployee_C:GamePadResetEmployee() end
function UWBP_ScheduleEmployee_C:GamePadMoreInfo() end
function UWBP_ScheduleEmployee_C:GamePadCheckAutoPay() end
function UWBP_ScheduleEmployee_C:OpenJobComboBox() end
---@param Increase boolean
function UWBP_ScheduleEmployee_C:GamePadSelectOptionFirstJob(Increase) end
function UWBP_ScheduleEmployee_C:OpenSecondJobComboBox() end
function UWBP_ScheduleEmployee_C:OpenShiftComboBox() end
---@param Increase boolean
function UWBP_ScheduleEmployee_C:GamePadSelectOptionSecondJob(Increase) end
---@param Increase boolean
function UWBP_ScheduleEmployee_C:GamePadSelectOptionShiftTime(Increase) end
function UWBP_ScheduleEmployee_C:OnInitialized() end
---@param bAppliedSetting boolean
function UWBP_ScheduleEmployee_C:UpdateShiftHouer(bAppliedSetting) end
function UWBP_ScheduleEmployee_C:OnFirstJobPicker() end
---@param EntryPoint int32
function UWBP_ScheduleEmployee_C:ExecuteUbergraph_WBP_ScheduleEmployee(EntryPoint) end


