---@meta

---@class UWBP_CampersStatus_C : UGSSBaseWidget
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AllAvaibleCampers UTextBlock
---@field Blocker1 UOverlay
---@field Blocker2 UOverlay
---@field Blocker3 UOverlay
---@field Blocker4 UOverlay
---@field Blocker5 UOverlay
---@field Blocker6 UOverlay
---@field Blocker7 UOverlay
---@field Blocker8 UOverlay
---@field BuyButtonOverlay UOverlay
---@field BuyCamperButton UGSSButton
---@field BuyTXT UTextBlock
---@field Camper1 UImage
---@field Camper2 UImage
---@field Camper3 UImage
---@field Camper4 UImage
---@field Camper5 UImage
---@field Camper6 UImage
---@field Camper7 UImage
---@field Camper8 UImage
---@field CaravanaDescriptionTXT UTextBlock
---@field CaravanasImage UImage
---@field HorizontalBox_62 UHorizontalBox
---@field Image_63 UImage
---@field Image_212 UImage
---@field Image_298 UImage
---@field Image_647 UImage
---@field Image_lock1 UImage
---@field Image_lock2 UImage
---@field Image_lock3 UImage
---@field Image_lock4 UImage
---@field Image_lock5 UImage
---@field Image_lock6 UImage
---@field Image_lock7 UImage
---@field Image_lock8 UImage
---@field InhabitedCampersTXT UTextBlock
---@field PriceTXT UTextBlock
---@field SetCaravanaNametTXT UTextBlock
---@field WBP_KeyHint_RightButton UWBP_KeyHint_C
---@field CurrentMap FName
---@field Maps TArray<FName>
---@field Shop ACentralShop
---@field MaxCaravanas int32
---@field EmployeRef UPC_Employe_C
---@field MapsToLoad TArray<FName>
---@field MapsToUnload TArray<FName>
---@field bCanLoad boolean
---@field Campers TArray<FCamperStruct>
---@field CurrentCamper FCamperStruct
---@field CamperSlots TArray<UWBP_CamperSlot_C>
---@field ArrayOfLoadedCaravanas TArray<AActor>
---@field NewEmployeeEventClass TSoftClassPtr<UGSSEvent>
---@field NewEmployeeEventTimer FTimerHandle
---@field SequenceWidget UWBP_SequenceSkip_C
---@field SequencePlayer ULevelSequencePlayer
---@field PrevMinigameState ECharacterState
local UWBP_CampersStatus_C = {}

---@param Visible boolean
function UWBP_CampersStatus_C:HintsVisibility(Visible) end
function UWBP_CampersStatus_C:CheckIfLastCamperIsOwned() end
function UWBP_CampersStatus_C:HandleAchievement() end
function UWBP_CampersStatus_C:SetCurrentCamperPrice() end
---@param Loaded UObject
function UWBP_CampersStatus_C:OnLoaded_7E011BDB450C250E96C1F185D1DB83FC(Loaded) end
function UWBP_CampersStatus_C:Construct() end
function UWBP_CampersStatus_C:BndEvt__BuyCamperButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature() end
function UWBP_CampersStatus_C:Refresh() end
function UWBP_CampersStatus_C:BndEvt__BuyCamperButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature() end
function UWBP_CampersStatus_C:BndEvt__BuyCamperButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature() end
function UWBP_CampersStatus_C:RefreshCounter() end
---@param Maps TArray<FName>
function UWBP_CampersStatus_C:HandleLoadingMaps(Maps) end
function UWBP_CampersStatus_C:FinishBuyingTrailer() end
---@param MapsUnload TArray<FName>
function UWBP_CampersStatus_C:HandleUnloadingMaps(MapsUnload) end
function UWBP_CampersStatus_C:SetVisuals() end
function UWBP_CampersStatus_C:LoadCamperLevels() end
function UWBP_CampersStatus_C:OnTimePassed() end
function UWBP_CampersStatus_C:SkipCutscene() end
function UWBP_CampersStatus_C:GamePadBuyCamper() end
function UWBP_CampersStatus_C:CustomEvent() end
function UWBP_CampersStatus_C:CustomEvent_1() end
---@param EntryPoint int32
function UWBP_CampersStatus_C:ExecuteUbergraph_WBP_CampersStatus(EntryPoint) end


